### ISSUE TITLE
feat 在现有根据分支来定位apk的基础上增加根据安装包名称来定位

### ISSUE THREAD

**Issue by shinyvince** [jenkinsci/sonic-ci-helper-plugin#39]
### What feature do you want to see added?

有的一次编译会生成多个apk（比如按国家区分），建议在现有根据分支来定位的方式上，增加根据安装包名称来定位的功能（正则表达式）

**Comment by yaming116** [comment]
https://github.com/jenkinsci/sonic-ci-helper-plugin/pull/45
