### ISSUE TITLE
question: 找不到Messages类

### ISSUE THREAD

**Issue by hatusyoki** [jenkinsci/sonic-ci-helper-plugin#49]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
java: 找不到符号
  符号:   类 Messages
  位置: 程序包 io.jenkins.plugins.sonic
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ide

### Reproduction steps

同步仓库后直接编译

### Expected Results

正常编译

### Actual Results

java: 找不到符号
  符号:   类 Messages
  位置: 程序包 io.jenkins.plugins.sonic

**Comment by ZhouYixun** [comment]
抱歉回复得不是那么及时。

Message类是本地类似lombok编译后出现的，你要先正确下载maven依赖

**Comment by ZhouYixun** [comment]
Jenkinsci组织得消息比较多，所以被刷下去了。后面如果比较紧急的话可以去 https://sonic-cloud.wiki/ 反馈

**Comment by hatusyoki** [comment]
> 抱歉回复得不是那么及时。
> 
> Message类是本地类似lombok编译后出现的，你要先正确下载maven依赖

处理好依赖问题后解决了

**Comment by ZhouYixun** [comment]
解决了就好
