### ISSUE TITLE
Is it possible to add the test result id into environment variables?

### ISSUE THREAD

**Issue by xiukei** [jenkinsci/sonic-ci-helper-plugin#53]
### What feature do you want to see added?

job需要关联测试报告，发现 sonic 插件的 output 会打印返回的测试报告 id，是否可以将测试报告id 写入环境变量？

I need to combine the sonic test result url after finishing the job. I found out the test result id would return when uploading to sonic. If it is possible to add the test result id into environment variables?

![image](https://github.com/jenkinsci/sonic-ci-helper-plugin/assets/49052467/00e8a1b5-b11c-46d8-a3ef-9876be734e30)

**Comment by ZhouYixun** [comment]
看到了你的pr了，可以的

**Comment by ZhouYixun** [comment]
https://github.com/jenkinsci/sonic-ci-helper-plugin/pull/54
